### ISSUE TITLE
New install, new init requires docutils

### ISSUE THREAD

**Issue by jackiekazil** [Anomareh/mynt#73]
Just set up a new install and ran an init on a new site. When I tried to run `mynt gen -f _site`, I got the following...  `ImportError: No module named docutils`.

It seems like docutils should be are part of mynt.  Since it is a small fix, I am going to submit an PR.... feel free to reject, as I do not understand all things mynt.

**Comment by Anomareh** [comment]
This should now be solved with v0.4.

The issue was the Docutils parser is included, but the dependencies are not required to be installed, but mynt would still try to parse any encountered reStructuredText files.

Now the user is notified when parsing a file fails and it is skipped.
